import Head from "next/head";
import { Inter } from "next/font/google";
import { getProductsInCollection } from "../../lib/shopify";
import ProductList from "../../components/ProductList";
import Hero from "../../components/Hero";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Foxes Beauty Boutique</title>
        <meta property="og:title" content="Foxes Beauty Boutique" />
        <meta property="og:type" content="website" />
        <meta
          property="og:url"
          content="https://shopify-store-nextjs-app.vercel.app/"
        />
        <meta
          property="og:image"
          content="https://shopify-store-nextjs-app.vercel.app/heroImg.png"
        />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta
          http-equiv="Content-Type"
          content="text/html; charset=ISO-8859-1"
        />
        /
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <ProductList products={products} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const products = await getProductsInCollection();

  return {
    props: { products },
  };
}
